name = "Abhishek Ajay"
license = "MIT"
licenselink = "https://github.com/yihui/hugo-xmin/blob/master/LICENSE.md"
description = "Abhishek Ajay's Personal Website"
homepage = "https://abhishekajay1718.github.io/personal/"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Yihui Xie"
  homepage = "https://yihui.name"
